### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by krishna-selectstar** [jedisct1/rust-qptrie#2]
If so, would you accept a PR to switch from `debug_unreachable` to `new_debug_unreachable`?  `new_debug_unreachable` is maintained and has no dependencies, and is licensed under MIT, so I think it should be fine to switch.

`debug_unreachable` looks unmaintained, and very old. So it uses hacks to work around a missing `unreachable_unchecked` in stdlib.

**Comment by jedisct1** [comment]
Sure!

The vast majority of Rust crates eventually get deprecated or abandoned, and it's not easy to keep track of all of them.

If `new_debug_unreachable` is the one to use now, let's do it :)
